# Cloudformation de um S3 bucket com permissões de escrita e leitura para todos que possuem a URL e a chave de acesso
# Output: URL e chave de acesso para o bucket

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: giropops-s3-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: 'AllowGetObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
            Condition:
              StringEquals:
                'aws:Referer': !Ref 'AWS::AccountId'
          - Sid: 'AllowPutObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
            Condition:
              StringEquals:
                'aws:Referer': !Ref 'AWS::AccountId'
Outputs:
  BucketURL:
    Value: !GetAtt MyS3Bucket.WebsiteURL
    Description: URL do bucket S3
  AccessKey:
    Value: !Ref MyS3Bucket
    Description: Chave de acesso ao bucket S3