name: Manual Delete

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      stack:
        description: 'Stack Name'
        required: true

jobs:
  cluster:
    name: Delete stack on AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region}}

    - name: Delete stack
      run: |
        aws cloudformation delete-stack \
          --stack-name ${{ github.event.inputs.stack }} \
          --region ${{ github.event.inputs.region }}
