AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: my-unique-bucket-name # Nome do bucket
Outputs:
  S3BucketURL:
    Value: !GetAtt MyS3Bucket.WebsiteURL
    Description: URL pública do bucket S3