name: Update

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      keypair:
        description: 'SSH Key Pair'
        default: 'PICK'
        required: true
      template-file:
        description: 'CloudFormation template file'
        required: true
        default: './giropops-infra.yaml'

jobs:
  cluster:
    name: Update stack on AWS
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region}}

    - name: Configure environment name
      id: env-name
      env:
        REPO: ${{ github.repository }}
      run: |
        ENVIRONMENT=`echo $REPO | tr "/" "-"`
        echo "Environment name: $ENVIRONMENT"
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

    - name: Update stack
      run: |
        aws cloudformation update-stack \
          --stack-name ${{ steps.env-name.outputs.environment }} \
          --template-body file://${{ github.event.inputs.template-file }} \
          --parameters ParameterKey=EnvironmentName,ParameterValue=${{ steps.env-name.outputs.environment }} \
          --capabilities CAPABILITY_IAM \
          --region ${{ github.event.inputs.region }}
